# Generated by Django 5.0.6 on 2026-07-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boucherie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(choices=[('commande', 'Commande'), ('partenariat', 'Partenariat'), ('information', 'Information'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_treated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
